version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./data:/app/data
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - FRONTEND_URL=http://localhost:3000
      - CHROMA_DB_PATH=/app/chroma_db
      - ENVIRONMENT=development
      - DEBUG=true
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - research-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - NODE_ENV=development
    networks:
      - research-network
    stdin_open: true
    tty: true

networks:
  research-network:
    driver: bridge

volumes:
  chroma_db:
    driver: local
  data:
    driver: local
